name: vai-lhc
version: 1.0
summary: Hello world application for LHC
description: |
  This is yet another hello-world clone ...
grade: stable
confinement: strict

apps:
  vai-lhc:
    command: bin/hello-lhc

parts:
  simple:
    plugin: make
    source: .
